apiVersion: apps/v1
kind: Deployment
metadata:
  name: website1
spec:
  replicas: 5
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        type: frontend
    spec:
      containers:
      - name: container1
        image: docman404/website1
        ports:
        - containerPort: 80
          protocol: TCP
